### ISSUE TITLE
Fails to detect literals after unary operators if they are separated by whitespace

### ISSUE THREAD

**Issue by techwiz24** [techwiz24/EECS2500#19]
```java
Enter the infix expression to convert and evaluate: Q 4
Encountered an error while evaluating the postfix expression: Malformed infix expression (missing literal for unary operator): 'Q 4'
java.lang.IllegalArgumentException: Malformed infix expression (missing literal for unary operator): 'Q 4'
	at edu.utoledo.nlowe.postfix.PostfixEngine.lambda$convertInfixExpression$12(PostfixEngine.java:94)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at edu.utoledo.nlowe.postfix.PostfixEngine.convertInfixExpression(PostfixEngine.java:91)
	at edu.utoledo.nlowe.postfix.samples.ConverterCalculator.main(ConverterCalculator.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by techwiz24** [comment]
This is because unary operator validation happens before stripping out the whitespace
